<?php

/**
 * @author Andrei Shilkov <aishilkov94@gmail.com>
 * @license MIT
 *
 * @see https://github.com/ashilkov/symfony-blog
 */

namespace App\Blog\Infrastructure\Repository;

use App\Blog\Domain\Model\Blog as DomainEntity;
use App\Blog\Domain\Model\EntityInterface;
use App\Blog\Domain\Repository\BlogRepositoryInterface;
use App\Blog\Infrastructure\Doctrine\Entity\Blog;
use App\Blog\Infrastructure\Doctrine\Entity\BlogUser;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;

/**
 * @extends ServiceEntityRepository<Blog>
 */
class BlogRepository extends AbstractRepository implements BlogRepositoryInterface
{
    public function getEntityType(): string
    {
        return Blog::class;
    }

    /**
     * @throws \Exception
     */
    public function findWithSubscriptions(?int $userId): array
    {
        $result = $this->createQueryBuilder('b')
            ->select('b as blog')
            ->addSelect('(CASE WHEN s.id IS NULL THEN 0 ELSE 1 END) AS subscribed')
            ->leftJoin('b.subscriptions', 's', 'WITH', 's.subscriberId = :userId AND s.blog = b')
            ->setParameter('userId', $userId)
            ->getQuery()
            ->getResult();

        foreach ($result as &$item) {
            $item['blog'] = $this->entityAssembler->toDomain($item['blog']);
        }

        return $result;
    }

    protected function saveAfter(EntityInterface|DomainEntity $entity, object $doctrineEntity): void
    {
        parent::saveAfter($entity, $doctrineEntity); // TODO: Change the autogenerated stub

        foreach ($entity->getBlogUsers() as $blogUser) {
            /** @var BlogUser $doctrineBlogUser */
            $doctrineBlogUser = $this->entityAssembler->toDoctrineEntity($blogUser);
            $doctrineBlogUser->blog = $this->entityManager->getReference(Blog::class, $doctrineEntity->id);
            $this->entityManager->persist($doctrineBlogUser);
        }

        $this->entityManager->flush();
    }
}
