api_platform:
    title: Hello API Platform
    version: 1.0.0
    enable_swagger_ui: true
    mapping:
        paths: [
            '%kernel.project_dir%/src/Blog/API/',
            '%kernel.project_dir%/src/User/API/'
        ]
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
    defaults:
        stateless: true
        cache_headers:
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
    graphql:
        graphiql:
            enabled: true
