controllers:
    resource:
        path: ../src/Blog/UI/Http/Controller/
        namespace: App\Blog\UI\Http\Controller
    type: attribute

api_login_check:
    path: /api/login

api_refresh_token:
    path: /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
